apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: p2p27xwjh-nodejs 
  janus-idp.io/tekton: p2p27xwjh-nodejs
  backstage.io/kubernetes-id: p2p27xwjh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p2p27xwjh-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml